name: saltstack-binddns-formula
source: https://github.com/bechtoldt/saltstack-binddns-formula
summary: SaltStack Formula to set up and configure BIND, a DNS software suite
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - ensure user+group exists?
  - support IPv6
